require("./array-element")
require("./array-ellipsis")
require("./array-pattern")
require("./array-wildcard")
require("./exact-property")
require("./negator")
require("./object-pattern")
require("./typed-value")
require("./wildcard-property")
require("./wildcard-value")

require("washington")("Use `tags` property in the object instead")
